version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: appAdmin
      POSTGRES_PASSWORD: appPass
    ports:
      - "5432:5432"
  dbClient:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: darius@mail.com
      PGADMIN_DEFAULT_PASSWORD: d
    ports:
      - "8800:80"